name: PR Pipeline

on:
    pull_request:
        branches: [dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install Aspire workload
      run: |
        dotnet workload install aspire

    - name: Restore dependencies
      run: /
        dotnet restore

# TO BE COMPLETE IN SUBSEQUENT pull_request